services:

  apache:
    ports:
      - ${PORT_APACHE_HOST}:${PORT_APACHE_CONTAINER}
    volumes:
      - ${VOLUME_APACHE}:/var/www/html
    environment:
      - DOC_ROOT=${DOC_ROOT}
    build:
      context: ./apache
      args:
        - XDEBUG=${XDEBUG}
        - PHP_APACHE_TAG=${PHP_APACHE_TAG}

  db:
    image: mariadb:10.11.7
    volumes:
      - ${VOLUME_DB}:/var/lib/mysql:Z
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
