version: '3.7'
services:
    db:
        image: mysql:5.7
        ports:
            - "${DB_HOST_PORT}:3306"
        volumes:
            - ${MYSQL_VOLUME}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    phpapache:
        build:
            context: ./phpapache
            args:
                - INSTALL_INTL=${PHP_INSTALL_INTL}
        ports:
            - "${PHPAPACHE_HOST_PORT}:80"
        volumes:
            - ./symfony:/var/www/html
        links:
            - db
