services:

  apache:
    ports:
      - "${PORT_APACHE_HOST}:80"
    volumes:
      - ${VOLUME_APACHE}:/var/www/html
    build:
      context: ./apache
      args:
        - XDEBUG=${XDEBUG}
        - PHP_APACHE_TAG=${PHP_APACHE_TAG}
        - DOC_ROOT=${DOC_ROOT}

  db:
    image: mariadb:10.11.7
    volumes:
      - ${VOLUME_DB}:/var/lib/mysql:Z
    ports:
      - "${PORT_DB_HOST}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}

  adminer:
    image: adminer
    ports:
      - ${PORT_ADMINER}:8080

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
