version: '3.7'
services:
    db:
        image: mysql:5.7
        ports:
            - "3307:3306"
        volumes:
            - /home/<user name>/dockofony-mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    phpapache:
        build: ./phpapache
        ports:
            - "8081:80"
        volumes:
            - ./symfony:/var/www/html
        links:
            - db
