services:
  symfony:
    build:
      context: ./service_symfony
      args:
        - XDEBUG=${XDEBUG}
    ports:
      - "${PORT_SYMFONY_HOST}:${PORT_SYMFONY_CONTAINER}"
    volumes:
      - ${VOLUME_SYMFONY}:/var/www/html
  db:
    image: mariadb:10.11.7
    volumes:
      - ${VOLUME_DB}:/var/lib/mysql:Z
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
  adminer:
    image: adminer
    ports:
      - ${PORT_ADMINER}:8080
